export const ENDPOINTS = {
  CONFIG: `https://music.amazon.com/config.json`,
  GLOBAL_SEARCH: `https://eu.mesk.skill.music.a2z.com/api/showSearch`,
  TRACKS_SEARCH: `https://eu.mesk.skill.music.a2z.com/api/searchCatalogTracks`,
  ALBUM_SEARCH: `https://eu.mesk.skill.music.a2z.com/api/searchCatalogAlbums`,
  ARTIST_SEARCH: `https://eu.mesk.skill.music.a2z.com/api/searchCatalogArtists`,
  PLAYLIST_SEARCH: `https://eu.mesk.skill.music.a2z.com/api/searchCatalogPlaylists`,
  COMMUNITY_PLAYLIST_SEARCH: `https://eu.mesk.skill.music.a2z.com/api/searchCommunityPlaylists`,
  TRACK_INFO: `https://eu.mesk.skill.music.a2z.com/api/cosmicTrack/displayCatalogTrack`,
  ALBUM_INFO: `https://eu.mesk.skill.music.a2z.com/api/showCatalogAlbum`,
  ARTIST_INFO: `https://eu.mesk.skill.music.a2z.com/api/explore/v1/showCatalogArtist`,
  ARTIST_TOP_TRACKS: `https://eu.mesk.skill.music.a2z.com/api/showCatalogTracks`,
  PLAYLIST_INFO: `https://eu.mesk.skill.music.a2z.com/api/showCatalogPlaylist`,
  COMMUNITY_PLAYLIST_INFO: `https://eu.mesk.skill.music.a2z.com/api/showLibraryPlaylist`,
};
